### ISSUE TITLE
Issue passing the key and cert in ClientSSLSecurity

### ISSUE THREAD

**Issue by ibmappcon** [loopbackio/strong-soap#293]
Hi,

I am trying to set the client SSL security using following code:

```
    client.setSecurity(new soap.ClientSSLSecurity(
      key
      , cert
      , {
        rejectUnauthorized: false
      }
    ))
```

key and cert are in following format:
`-----BEGIN CERTIFICATE-----<!redacted>`

If i use them in the constructor as it is, the method takes this as a string Path to the file, hence, returns error from readFileSync.

I also tried to convert the key and cert into a buffer, but then the following error is returned:
```
{ Error: error:0909006C:PEM routines:get_name:no start line
    at Object.createSecureContext (_tls_common.js:135:17)
    at Object.connect (_tls_wrap.js:1130:48)
    at Agent.createConnection (https.js:120:22)
    at Agent.createSocket (_http_agent.js:227:26)
    at Agent.addRequest (_http_agent.js:185:10)
    at new ClientRequest (_http_client.js:249:16)
    at Object.request (https.js:289:10)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5) combinedErrorValue: 'REQUEST_ERROR' }

```
Please let us know if there is any other way to pass the key and cert to ClientSSLSecurity without actually writing the key and cert in file.

Thank You

**Comment by raymondfeng** [comment]
You can pass in values as `buffer`.
