### ISSUE TITLE
Fix broken tests in Node.js >= v18

### ISSUE THREAD

**Issue by achrinza** [loopbackio/strong-soap#650]
This issue is to track the failing tests in Node.js >= v18.

These failing tests can be observed in https://github.com/loopbackio/strong-soap/pull/648.

| Node.js version | No. of failing tests
|-|-
| v18 | 2
| v20 | 3
| v21 | 3

<details>
<summary>Node.js v18 failing test logs</summary>

```
  1) NTLM Auth tests
       should call ntlm endpoint:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/strong-soap/strong-soap/test/client-ntlm-test.js)
      at listOnTimeout (node:internal/timers:569:17)
      at process.processTimers (node:internal/timers:512:7)

  2) SOAP Server
       should pass the original req to async methods:

      Uncaught AssertionError: expected '1' to be '127.0.0.1'
      + expected - actual

      -1
      +127.0.0.1
      
      at Assertion.fail (node_modules/should/cjs/should.js:275:17)
      at Assertion.value (node_modules/should/cjs/should.js:356:19)
      at /home/runner/work/strong-soap/strong-soap/test/server-test.js:300:56
      at /home/runner/work/strong-soap/strong-soap/src/client.js:26:885
      at Request._callback (src/http.js:34:560)
      at self.callback (node_modules/request/request.js:185:22)
      at Request.emit (node:events:517:28)
      at Request.<anonymous> (node_modules/request/request.js:1154:10)
      at Request.emit (node:events:517:28)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1076:12)
      at Object.onceWrapper (node:events:631:28)
      at IncomingMessage.emit (node:events:529:35)
      at endReadableNT (node:internal/streams/readable:1368:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```
</details>

<details>
<summary>Node.js v20 failing test logs</summary>

```
1) NTLM Auth tests
       should call ntlm endpoint:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/strong-soap/strong-soap/test/client-ntlm-test.js)
      at listOnTimeout (node:internal/timers:573:17)
      at process.processTimers (node:internal/timers:514:7)

  2) SOAP Server
       should pass the original req to async methods:

      Uncaught AssertionError: expected '1' to be '127.0.0.1'
      + expected - actual

      -1
      +127.0.0.1
      
      at Assertion.fail (node_modules/should/cjs/should.js:275:17)
      at Assertion.value (node_modules/should/cjs/should.js:356:19)
      at /home/runner/work/strong-soap/strong-soap/test/server-test.js:300:56
      at /home/runner/work/strong-soap/strong-soap/src/client.js:26:885
      at Request._callback (src/http.js:34:560)
      at self.callback (node_modules/request/request.js:185:22)
      at Request.emit (node:events:514:28)
      at Request.<anonymous> (node_modules/request/request.js:1154:10)
      at Request.emit (node:events:514:28)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1076:12)
      at Object.onceWrapper (node:events:628:28)
      at IncomingMessage.emit (node:events:526:35)
      at endReadableNT (node:internal/streams/readable:1408:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

  3) wsdl-tests
       wsdl parsing test cases
         should not parse connection error:
     Uncaught 
  AggregateError
      at internalConnectMultiple (node:net:1114:18)
      at afterConnectMultiple (node:net:1667:5)
```
</details>

<details>
<summary>Node.js v21 failing test logs</summary>

```

  1) NTLM Auth tests
       should call ntlm endpoint:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/strong-soap/strong-soap/test/client-ntlm-test.js)
      at listOnTimeout (node:internal/timers:573:17)
      at process.processTimers (node:internal/timers:514:7)

  2) SOAP Server
       should pass the original req to async methods:

      Uncaught AssertionError: expected '1' to be '127.0.0.1'
      + expected - actual

      -1
      +127.0.0.1
      
      at Assertion.fail (node_modules/should/cjs/should.js:275:17)
      at Assertion.value (node_modules/should/cjs/should.js:356:19)
      at /home/runner/work/strong-soap/strong-soap/test/server-test.js:300:56
      at /home/runner/work/strong-soap/strong-soap/src/client.js:26:885
      at Request._callback (src/http.js:34:560)
      at self.callback (node_modules/request/request.js:185:22)
      at Request.emit (node:events:515:28)
      at Request.<anonymous> (node_modules/request/request.js:1154:10)
      at Request.emit (node:events:515:28)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1076:12)
      at Object.onceWrapper (node:events:629:28)
      at IncomingMessage.emit (node:events:527:35)
      at endReadableNT (node:internal/streams/readable:1589:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

  3) wsdl-tests
       wsdl parsing test cases
         should not parse connection error:
     Uncaught 
  AggregateError
      at internalConnectMultiple (node:net:1114:18
```
</details>

**Comment by dhmlau** [comment]
Fixed via PR #672.
